import { makeCard, makeDisc, makeLightstick } from './artwork.js'

export const goodsMasters = [
  {
    id: 'gm-1',
    group: 'NewJeans',
    artist: 'NewJeans',
    eraOrAlbum: 'Get Up',
    merchType: 'album',
    title: 'Get Up (Bunny Beach Ver.)',
    images: [makeDisc('#0b0d11', '#d5f1ff')],
    tags: ['앨범', '포토북'],
  },
  {
    id: 'gm-2',
    group: 'LE SSERAFIM',
    artist: 'LE SSERAFIM',
    eraOrAlbum: 'EASY',
    merchType: 'photocard',
    title: 'Weverse Photocard Set',
    images: [makeCard('#10131a', '#d5ebff')],
    tags: ['포토카드', '특전', '위버스'],
  },
  {
    id: 'gm-3',
    group: 'SEVENTEEN',
    artist: 'SEVENTEEN',
    eraOrAlbum: 'Light Stick',
    merchType: 'lightstick',
    title: 'Light Stick v3',
    images: [makeLightstick('#0b0d11', '#cfe8ff')],
    tags: ['응원봉', '공식'],
  },
  {
    id: 'gm-4',
    group: 'BLACKPINK',
    artist: 'BLACKPINK',
    eraOrAlbum: 'BORN PINK',
    merchType: 'album',
    title: 'Signed CD',
    images: [makeDisc('#111', '#f5d2df')],
    tags: ['사인', '한정'],
  },
  {
    id: 'gm-5',
    group: 'IVE',
    artist: 'IVE',
    eraOrAlbum: 'IVE SWITCH',
    merchType: 'album',
    title: 'Photobook Ver.',
    images: [makeDisc('#0e1218', '#f0e8ff')],
    tags: ['앨범', '포토북'],
  },
  {
    id: 'gm-6',
    group: 'Stray Kids',
    artist: 'Stray Kids',
    eraOrAlbum: '5-STAR',
    merchType: 'md',
    title: 'Tour Hoodie (Black)',
    images: [makeCard('#0d0d0d', '#ffe7ba')],
    tags: ['의류', '공식MD'],
  },
  {
    id: 'gm-7',
    group: 'BTS',
    artist: 'BTS',
    eraOrAlbum: 'Proof',
    merchType: 'dvd',
    title: 'Collector DVD',
    images: [makeDisc('#111722', '#dce3ff')],
    tags: ['DVD', '한정'],
  },
  {
    id: 'gm-8',
    group: 'Aespa',
    artist: 'Aespa',
    eraOrAlbum: 'Drama',
    merchType: 'photocard',
    title: 'Lucky Draw Photocard',
    images: [makeCard('#10131a', '#d5ebff')],
    tags: ['포토카드', '특전', '위버스'],
  },
  {
    id: 'gm-9',
    group: 'NCT 127',
    artist: 'NCT 127',
    eraOrAlbum: 'Fact Check',
    merchType: 'album',
    title: 'Gate Ver.',
    images: [makeDisc('#0b0d11', '#f4d9e5')],
    tags: ['앨범', '포토북'],
  },
  {
    id: 'gm-10',
    group: 'Red Velvet',
    artist: 'Red Velvet',
    eraOrAlbum: 'Chill Kill',
    merchType: 'album',
    title: 'Bag Ver.',
    images: [makeDisc('#0e1218', '#f0e8ff')],
    tags: ['앨범', '포토북'],
  },
  {
    id: 'gm-11',
    group: 'TXT',
    artist: 'TXT',
    eraOrAlbum: 'Freefall',
    merchType: 'md',
    title: 'Official Pouch',
    images: [makeCard('#0d0d0d', '#ffe7ba')],
    tags: ['굿즈', '특전'],
  },
]

export const variants = [
  {
    id: 'v-1',
    goodsMasterId: 'gm-1',
    member: 'ALL',
    version: 'Bunny Beach',
    releaseRound: '1st',
    attributes: {
      eventType: '앨범 특전',
      hologram: '없음',
      frameColor: 'Blue',
      numbering: 'N/A',
      specialMark: 'Sticker',
    },
  },
  {
    id: 'v-2',
    goodsMasterId: 'gm-2',
    member: 'Kazuha',
    version: 'Weverse',
    releaseRound: 'POB',
    attributes: {
      eventType: '위버스 특전',
      hologram: '있음',
      frameColor: 'Silver',
      numbering: 'N/A',
      specialMark: 'Star Stamp',
    },
  },
  {
    id: 'v-3',
    goodsMasterId: 'gm-3',
    member: 'ALL',
    version: 'v3',
    releaseRound: '2024',
    attributes: {
      eventType: '공식 MD',
      hologram: '있음',
      frameColor: 'N/A',
      numbering: 'A-1221',
      specialMark: 'Sealed',
    },
  },
  {
    id: 'v-4',
    goodsMasterId: 'gm-4',
    member: 'Jisoo',
    version: 'Signed',
    releaseRound: 'Limited',
    attributes: {
      eventType: '사인',
      hologram: '없음',
      frameColor: 'Black',
      numbering: 'S-0941',
      specialMark: 'Signature',
    },
  },
  {
    id: 'v-5',
    goodsMasterId: 'gm-5',
    member: 'Wonyoung',
    version: 'Photobook',
    releaseRound: '1st',
    attributes: {
      eventType: '앨범 특전',
      hologram: '없음',
      frameColor: 'Lilac',
      numbering: 'N/A',
      specialMark: 'Postcard',
    },
  },
  {
    id: 'v-6',
    goodsMasterId: 'gm-6',
    member: 'ALL',
    version: 'Hoodie',
    releaseRound: 'Tour',
    attributes: {
      eventType: '공식 MD',
      hologram: '있음',
      frameColor: 'N/A',
      numbering: 'SKZ-552',
      specialMark: 'Size L',
    },
  },
  {
    id: 'v-7',
    goodsMasterId: 'gm-7',
    member: 'ALL',
    version: 'Collector',
    releaseRound: 'Limited',
    attributes: {
      eventType: 'DVD',
      hologram: '없음',
      frameColor: 'N/A',
      numbering: 'P-210',
      specialMark: 'Photo Set',
    },
  },
  {
    id: 'v-8',
    goodsMasterId: 'gm-8',
    member: 'Karina',
    version: 'Lucky Draw',
    releaseRound: 'Weverse',
    attributes: {
      eventType: '위버스 특전',
      hologram: '있음',
      frameColor: 'Silver',
      numbering: 'N/A',
      specialMark: 'Lucky Stamp',
    },
  },
  {
    id: 'v-9',
    goodsMasterId: 'gm-9',
    member: 'Taeyong',
    version: 'Gate',
    releaseRound: '1st',
    attributes: {
      eventType: '앨범 특전',
      hologram: '없음',
      frameColor: 'Red',
      numbering: 'N/A',
      specialMark: 'Poster',
    },
  },
  {
    id: 'v-10',
    goodsMasterId: 'gm-10',
    member: 'Irene',
    version: 'Bag',
    releaseRound: 'Limited',
    attributes: {
      eventType: '앨범 특전',
      hologram: '없음',
      frameColor: 'Pearl',
      numbering: 'N/A',
      specialMark: 'Bag Pack',
    },
  },
  {
    id: 'v-11',
    goodsMasterId: 'gm-11',
    member: 'ALL',
    version: 'Pouch',
    releaseRound: 'Tour',
    attributes: {
      eventType: '공식 MD',
      hologram: '있음',
      frameColor: 'N/A',
      numbering: 'TXT-110',
      specialMark: 'Zip',
    },
  },
]

export const sellers = [
  {
    id: 'u-1',
    nickname: 'MintLab',
    rating: 4.9,
    totalTrades: 312,
    disputeRate: 0.3,
    status: 'active',
  },
  {
    id: 'u-2',
    nickname: 'BlueEcho',
    rating: 4.7,
    totalTrades: 124,
    disputeRate: 0.6,
    status: 'active',
  },
  {
    id: 'u-3',
    nickname: 'LightHaus',
    rating: 4.8,
    totalTrades: 205,
    disputeRate: 0.2,
    status: 'active',
  },
  {
    id: 'u-4',
    nickname: 'SignedLab',
    rating: 5.0,
    totalTrades: 79,
    disputeRate: 0.0,
    status: 'active',
  },
  {
    id: 'u-5',
    nickname: 'VelvetRoom',
    rating: 4.6,
    totalTrades: 64,
    disputeRate: 0.8,
    status: 'active',
  },
  {
    id: 'u-6',
    nickname: 'ArchiveBox',
    rating: 4.8,
    totalTrades: 132,
    disputeRate: 0.4,
    status: 'active',
  },
  {
    id: 'u-7',
    nickname: 'WeversePick',
    rating: 4.7,
    totalTrades: 88,
    disputeRate: 0.5,
    status: 'active',
  },
  {
    id: 'u-8',
    nickname: 'GateRoom',
    rating: 4.6,
    totalTrades: 51,
    disputeRate: 0.9,
    status: 'active',
  },
  {
    id: 'u-9',
    nickname: 'SoftBag',
    rating: 4.9,
    totalTrades: 117,
    disputeRate: 0.2,
    status: 'active',
  },
]

export const listings = [
  {
    id: 'l-1',
    sellerId: 'u-1',
    variantId: 'v-1',
    conditionGrade: 'S',
    conditionDetails: ['미개봉', '박스 손상 없음'],
    includes: {
      pob: true,
      sleeve: true,
      case: true,
      albumInclusions: ['포토북', '포토카드 5장', '스티커'],
    },
    photos: [makeDisc('#0b0d11', '#d5f1ff')],
    price: 48000,
    quantity: 12,
    saleType: 'fixed',
    status: 'active',
    shippingPolicyId: 'ship-1',
    createdAt: '2026-01-07',
  },
  {
    id: 'l-2',
    sellerId: 'u-2',
    variantId: 'v-2',
    conditionGrade: 'A',
    conditionDetails: ['미세 스크래치'],
    includes: {
      pob: true,
      sleeve: false,
      case: false,
      albumInclusions: ['포토카드 1장'],
    },
    photos: [makeCard('#10131a', '#d5ebff')],
    price: 18000,
    quantity: 20,
    saleType: 'offer',
    status: 'active',
    shippingPolicyId: 'ship-2',
    createdAt: '2026-01-07',
  },
  {
    id: 'l-3',
    sellerId: 'u-3',
    variantId: 'v-3',
    conditionGrade: 'A',
    conditionDetails: ['박스 미세 눌림'],
    includes: {
      pob: false,
      sleeve: true,
      case: true,
      albumInclusions: ['구성품 올인'],
    },
    photos: [makeLightstick('#0b0d11', '#cfe8ff')],
    price: 62000,
    quantity: 9,
    saleType: 'fixed',
    status: 'active',
    shippingPolicyId: 'ship-1',
    createdAt: '2026-01-06',
  },
  {
    id: 'l-4',
    sellerId: 'u-4',
    variantId: 'v-4',
    conditionGrade: 'S',
    conditionDetails: ['사인 선명', '하자 없음'],
    includes: {
      pob: true,
      sleeve: true,
      case: true,
      albumInclusions: ['사인 카드', '포토북', '포스터'],
    },
    photos: [makeDisc('#111', '#f5d2df')],
    price: 189000,
    quantity: 3,
    saleType: 'offer',
    status: 'active',
    shippingPolicyId: 'ship-3',
    createdAt: '2026-01-05',
  },
  {
    id: 'l-5',
    sellerId: 'u-5',
    variantId: 'v-5',
    conditionGrade: 'A',
    conditionDetails: ['포토북 미세 눌림'],
    includes: {
      pob: false,
      sleeve: true,
      case: true,
      albumInclusions: ['포토북', '포토카드 2장'],
    },
    photos: [makeDisc('#0e1218', '#f0e8ff')],
    price: 39000,
    quantity: 7,
    saleType: 'fixed',
    status: 'active',
    shippingPolicyId: 'ship-1',
    createdAt: '2026-01-04',
  },
  {
    id: 'l-6',
    sellerId: 'u-5',
    variantId: 'v-6',
    conditionGrade: 'B',
    conditionDetails: ['미세 보풀', '택 제거'],
    includes: {
      pob: false,
      sleeve: false,
      case: false,
      albumInclusions: ['후디 1장'],
    },
    photos: [makeCard('#0d0d0d', '#ffe7ba')],
    price: 52000,
    quantity: 5,
    saleType: 'offer',
    status: 'active',
    shippingPolicyId: 'ship-2',
    createdAt: '2026-01-03',
  },
  {
    id: 'l-7',
    sellerId: 'u-6',
    variantId: 'v-7',
    conditionGrade: 'S',
    conditionDetails: ['미개봉'],
    includes: {
      pob: true,
      sleeve: true,
      case: true,
      albumInclusions: ['DVD', '포토카드', '포토북'],
    },
    photos: [makeDisc('#111722', '#dce3ff')],
    price: 78000,
    quantity: 4,
    saleType: 'fixed',
    status: 'active',
    shippingPolicyId: 'ship-3',
    createdAt: '2026-01-02',
  },
  {
    id: 'l-8',
    sellerId: 'u-7',
    variantId: 'v-8',
    conditionGrade: 'A',
    conditionDetails: ['모서리 미세 스크래치'],
    includes: {
      pob: true,
      sleeve: false,
      case: false,
      albumInclusions: ['포토카드 1장'],
    },
    photos: [makeCard('#10131a', '#d5ebff')],
    price: 23000,
    quantity: 14,
    saleType: 'offer',
    status: 'active',
    shippingPolicyId: 'ship-2',
    createdAt: '2026-01-01',
  },
  {
    id: 'l-9',
    sellerId: 'u-8',
    variantId: 'v-9',
    conditionGrade: 'S',
    conditionDetails: ['미개봉'],
    includes: {
      pob: true,
      sleeve: true,
      case: true,
      albumInclusions: ['포토북', '포토카드 1장', '포스터'],
    },
    photos: [makeDisc('#0b0d11', '#f4d9e5')],
    price: 45000,
    quantity: 11,
    saleType: 'fixed',
    status: 'active',
    shippingPolicyId: 'ship-1',
    createdAt: '2025-12-30',
  },
  {
    id: 'l-10',
    sellerId: 'u-9',
    variantId: 'v-10',
    conditionGrade: 'A',
    conditionDetails: ['구성품 일부 비닐 사용감'],
    includes: {
      pob: false,
      sleeve: true,
      case: true,
      albumInclusions: ['포토북', '포토카드 2장', '가방'],
    },
    photos: [makeDisc('#0e1218', '#f0e8ff')],
    price: 52000,
    quantity: 6,
    saleType: 'fixed',
    status: 'active',
    shippingPolicyId: 'ship-1',
    createdAt: '2025-12-28',
  },
  {
    id: 'l-11',
    sellerId: 'u-7',
    variantId: 'v-11',
    conditionGrade: 'B',
    conditionDetails: ['로고 프린트 미세 마모'],
    includes: {
      pob: false,
      sleeve: false,
      case: false,
      albumInclusions: ['파우치 1개'],
    },
    photos: [makeCard('#0d0d0d', '#ffe7ba')],
    price: 28000,
    quantity: 9,
    saleType: 'offer',
    status: 'active',
    shippingPolicyId: 'ship-2',
    createdAt: '2025-12-27',
  },
]

export const priceIndex = [
  { variantId: 'v-1', conditionGrade: 'S', period: '7d', medianPrice: 47000, averagePrice: 46500, lastTradePrice: 48000, tradeCount: 42 },
  { variantId: 'v-2', conditionGrade: 'A', period: '30d', medianPrice: 17000, averagePrice: 17600, lastTradePrice: 18000, tradeCount: 81 },
  { variantId: 'v-3', conditionGrade: 'A', period: '7d', medianPrice: 60000, averagePrice: 61500, lastTradePrice: 62000, tradeCount: 18 },
  { variantId: 'v-4', conditionGrade: 'S', period: 'all', medianPrice: 185000, averagePrice: 189000, lastTradePrice: 189000, tradeCount: 9 },
  { variantId: 'v-5', conditionGrade: 'A', period: '7d', medianPrice: 38000, averagePrice: 39500, lastTradePrice: 39000, tradeCount: 28 },
  { variantId: 'v-6', conditionGrade: 'B', period: '30d', medianPrice: 50000, averagePrice: 51000, lastTradePrice: 52000, tradeCount: 13 },
  { variantId: 'v-7', conditionGrade: 'S', period: 'all', medianPrice: 76000, averagePrice: 77000, lastTradePrice: 78000, tradeCount: 21 },
  { variantId: 'v-8', conditionGrade: 'A', period: '7d', medianPrice: 22000, averagePrice: 22800, lastTradePrice: 23000, tradeCount: 35 },
  { variantId: 'v-9', conditionGrade: 'S', period: '30d', medianPrice: 44000, averagePrice: 44500, lastTradePrice: 45000, tradeCount: 26 },
  { variantId: 'v-10', conditionGrade: 'A', period: '7d', medianPrice: 50000, averagePrice: 51500, lastTradePrice: 52000, tradeCount: 19 },
  { variantId: 'v-11', conditionGrade: 'B', period: '30d', medianPrice: 26000, averagePrice: 27000, lastTradePrice: 28000, tradeCount: 12 },
]

export const priceHistory = {
  'v-1': [43000, 44500, 46000, 45500, 47000, 48000, 47500],
  'v-2': [15000, 16000, 17000, 16500, 17200, 18000, 17500],
  'v-3': [56000, 58000, 60000, 59000, 61000, 62000, 61500],
  'v-4': [175000, 180000, 182000, 185000, 186000, 189000, 188000],
  'v-5': [34000, 35500, 36000, 37200, 38000, 39000, 38800],
  'v-6': [47000, 49000, 50000, 51000, 52000, 51500, 51800],
  'v-7': [70000, 72000, 74000, 75000, 76000, 78000, 77500],
  'v-8': [18000, 19500, 20500, 21500, 22000, 23000, 22800],
  'v-9': [39000, 40500, 42000, 43000, 44000, 45000, 44800],
  'v-10': [45000, 47000, 49000, 50000, 51000, 52000, 51500],
  'v-11': [24000, 25000, 26000, 26500, 27000, 28000, 27500],
}

export const shippingPolicies = {
  'ship-1': { name: '일반 배송', fee: 4000, eta: '1-2일' },
  'ship-2': { name: '반값 택배', fee: 2500, eta: '2-3일' },
  'ship-3': { name: '프리미엄 배송', fee: 6000, eta: '당일/익일' },
}

export const offers = [
  { id: 'of-1', listingId: 'l-2', buyerId: 'u-9', price: 16500, status: '대기' },
  { id: 'of-2', listingId: 'l-4', buyerId: 'u-7', price: 182000, status: '카운터' },
]

export const orders = [
  {
    id: 'o-1',
    listingId: 'l-1',
    buyerId: 'u-8',
    finalPrice: 48000,
    platformFee: 2400,
    shippingFee: 4000,
    status: 'shipped',
    trackingNumber: 'CJ1234',
    timestamps: { paid: '오늘 10:00', shipped: '오늘 14:20' },
  },
]
