import { makeCard, makeDisc } from './artwork.js'

export const goodsMasters = [
  {
    id: 'gm-1',
    group: 'Neon Shore Records',
    artist: 'Luna Park',
    eraOrAlbum: 'Afterglow',
    merchType: 'LP',
    title: 'Afterglow (Gatefold LP)',
    images: [makeDisc('#0b0d11', '#d5f1ff')],
    tags: ['LP', '게이트폴드', '컬러반'],
  },
  {
    id: 'gm-2',
    group: 'Midnight Studio',
    artist: 'City Sunset',
    eraOrAlbum: 'Downtown Echo',
    merchType: 'CD',
    title: 'Downtown Echo (First Press)',
    images: [makeDisc('#10131a', '#d5ebff')],
    tags: ['CD', '초판', '스티커'],
  },
  {
    id: 'gm-3',
    group: 'Northwind Music',
    artist: 'River & Stone',
    eraOrAlbum: 'Live 1998',
    merchType: 'DVD',
    title: 'Live 1998 (2DVD)',
    images: [makeDisc('#0b0d11', '#cfe8ff')],
    tags: ['라이브', 'DVD', '한정'],
  },
  {
    id: 'gm-4',
    group: 'Analog Days',
    artist: 'Monochrome',
    eraOrAlbum: 'Tape Stories',
    merchType: '카세트',
    title: 'Tape Stories (Limited)',
    images: [makeCard('#111', '#f5d2df')],
    tags: ['카세트', '한정', '복각'],
  },
  {
    id: 'gm-5',
    group: 'Cedar Records',
    artist: 'Paper Moon',
    eraOrAlbum: 'Letters',
    merchType: 'LP',
    title: 'Letters (180g Remaster)',
    images: [makeDisc('#0e1218', '#f0e8ff')],
    tags: ['LP', '리마스터', '180g'],
  },
  {
    id: 'gm-6',
    group: 'Seoul Sound',
    artist: 'Blue Hour',
    eraOrAlbum: 'Blue Hour EP',
    merchType: 'CD',
    title: 'Blue Hour EP',
    images: [makeDisc('#0d0d0d', '#ffe7ba')],
    tags: ['CD', 'EP', '미개봉'],
  },
  {
    id: 'gm-7',
    group: 'Aria Works',
    artist: 'Glass Motel',
    eraOrAlbum: 'Noir',
    merchType: '박스셋',
    title: 'Noir Deluxe Box',
    images: [makeDisc('#111722', '#dce3ff')],
    tags: ['박스셋', '한정', '포스터'],
  },
  {
    id: 'gm-8',
    group: 'Nostalgia Lab',
    artist: 'June & July',
    eraOrAlbum: 'Seaside',
    merchType: 'LP',
    title: 'Seaside (Picture Disc)',
    images: [makeDisc('#10131a', '#d5ebff')],
    tags: ['LP', '픽처디스크', '컬러'],
  },
  {
    id: 'gm-9',
    group: 'Silverline',
    artist: 'Urban Tale',
    eraOrAlbum: 'Chapter 2',
    merchType: 'CD',
    title: 'Chapter 2 (Signed Booklet)',
    images: [makeDisc('#0b0d11', '#f4d9e5')],
    tags: ['CD', '사인', '한정'],
  },
  {
    id: 'gm-10',
    group: 'Echo Valley',
    artist: 'The Travelers',
    eraOrAlbum: 'Road Map',
    merchType: 'LP',
    title: 'Road Map (Blue Vinyl)',
    images: [makeDisc('#0e1218', '#f0e8ff')],
    tags: ['LP', '컬러반', '초판'],
  },
  {
    id: 'gm-11',
    group: 'Moonlight Press',
    artist: 'Seoul Night',
    eraOrAlbum: 'Night Drive',
    merchType: '카세트',
    title: 'Night Drive (Reissue)',
    images: [makeCard('#0d0d0d', '#ffe7ba')],
    tags: ['카세트', '리이슈', '소량'],
  },
]

export const variants = [
  {
    id: 'v-1',
    goodsMasterId: 'gm-1',
    member: 'Side A/B',
    version: 'Gatefold',
    releaseRound: '1st',
    attributes: {
      eventType: '초판',
      hologram: '없음',
      frameColor: 'Cobalt',
      numbering: 'N/A',
      specialMark: 'OBI 포함',
    },
  },
  {
    id: 'v-2',
    goodsMasterId: 'gm-2',
    member: 'Disc 1',
    version: 'First Press',
    releaseRound: '1st',
    attributes: {
      eventType: '초판',
      hologram: '없음',
      frameColor: 'Silver',
      numbering: 'N/A',
      specialMark: 'Sticker Sheet',
    },
  },
  {
    id: 'v-3',
    goodsMasterId: 'gm-3',
    member: 'Disc 1-2',
    version: '2DVD',
    releaseRound: 'Limited',
    attributes: {
      eventType: '라이브',
      hologram: '있음',
      frameColor: 'N/A',
      numbering: 'LR-1998',
      specialMark: 'Sealed',
    },
  },
  {
    id: 'v-4',
    goodsMasterId: 'gm-4',
    member: 'Side A/B',
    version: 'Limited',
    releaseRound: '2022',
    attributes: {
      eventType: '복각',
      hologram: '없음',
      frameColor: 'Smoke',
      numbering: 'CS-024',
      specialMark: 'Limited Stamp',
    },
  },
  {
    id: 'v-5',
    goodsMasterId: 'gm-5',
    member: 'Side A/B',
    version: 'Remaster',
    releaseRound: '2nd',
    attributes: {
      eventType: '리마스터',
      hologram: '없음',
      frameColor: 'Ivory',
      numbering: 'N/A',
      specialMark: '180g',
    },
  },
  {
    id: 'v-6',
    goodsMasterId: 'gm-6',
    member: 'Disc 1',
    version: 'EP',
    releaseRound: '2023',
    attributes: {
      eventType: 'EP',
      hologram: '없음',
      frameColor: 'N/A',
      numbering: 'BH-031',
      specialMark: 'Sealed',
    },
  },
  {
    id: 'v-7',
    goodsMasterId: 'gm-7',
    member: 'Disc 1-4',
    version: 'Deluxe',
    releaseRound: 'Limited',
    attributes: {
      eventType: '박스셋',
      hologram: '있음',
      frameColor: 'N/A',
      numbering: 'NX-210',
      specialMark: 'Numbered',
    },
  },
  {
    id: 'v-8',
    goodsMasterId: 'gm-8',
    member: 'Side A/B',
    version: 'Picture Disc',
    releaseRound: '2024',
    attributes: {
      eventType: '컬러반',
      hologram: '없음',
      frameColor: 'Aqua',
      numbering: 'N/A',
      specialMark: 'Picture',
    },
  },
  {
    id: 'v-9',
    goodsMasterId: 'gm-9',
    member: 'Disc 1',
    version: 'Signed',
    releaseRound: '1st',
    attributes: {
      eventType: '사인',
      hologram: '없음',
      frameColor: 'Burgundy',
      numbering: 'SG-088',
      specialMark: 'Signed Booklet',
    },
  },
  {
    id: 'v-10',
    goodsMasterId: 'gm-10',
    member: 'Side A/B',
    version: 'Blue Vinyl',
    releaseRound: '1st',
    attributes: {
      eventType: '컬러반',
      hologram: '없음',
      frameColor: 'Blue',
      numbering: 'N/A',
      specialMark: 'OBI 포함',
    },
  },
  {
    id: 'v-11',
    goodsMasterId: 'gm-11',
    member: 'Side A/B',
    version: 'Reissue',
    releaseRound: '2021',
    attributes: {
      eventType: '리이슈',
      hologram: '없음',
      frameColor: 'N/A',
      numbering: 'ND-110',
      specialMark: 'J-card',
    },
  },
]

export const sellers = [
  {
    id: 'u-1',
    nickname: 'MintLab',
    rating: 4.9,
    totalTrades: 312,
    disputeRate: 0.3,
    status: 'active',
  },
  {
    id: 'u-2',
    nickname: 'BlueEcho',
    rating: 4.7,
    totalTrades: 124,
    disputeRate: 0.6,
    status: 'active',
  },
  {
    id: 'u-3',
    nickname: 'LightHaus',
    rating: 4.8,
    totalTrades: 205,
    disputeRate: 0.2,
    status: 'active',
  },
  {
    id: 'u-4',
    nickname: 'SignedLab',
    rating: 5.0,
    totalTrades: 79,
    disputeRate: 0.0,
    status: 'active',
  },
  {
    id: 'u-5',
    nickname: 'VelvetRoom',
    rating: 4.6,
    totalTrades: 64,
    disputeRate: 0.8,
    status: 'active',
  },
  {
    id: 'u-6',
    nickname: 'ArchiveBox',
    rating: 4.8,
    totalTrades: 132,
    disputeRate: 0.4,
    status: 'active',
  },
  {
    id: 'u-7',
    nickname: 'VinylCrew',
    rating: 4.7,
    totalTrades: 88,
    disputeRate: 0.5,
    status: 'active',
  },
  {
    id: 'u-8',
    nickname: 'TapeRoom',
    rating: 4.6,
    totalTrades: 51,
    disputeRate: 0.9,
    status: 'active',
  },
  {
    id: 'u-9',
    nickname: 'CobaltSound',
    rating: 4.9,
    totalTrades: 117,
    disputeRate: 0.2,
    status: 'active',
  },
]

export const listings = [
  {
    id: 'l-1',
    sellerId: 'u-1',
    variantId: 'v-1',
    conditionGrade: 'S',
    conditionDetails: ['미개봉', '커버 손상 없음'],
    includes: {
      pob: true,
      sleeve: true,
      case: true,
      albumInclusions: ['가사지', '포스터', '라이너 노트'],
    },
    photos: [makeDisc('#0b0d11', '#d5f1ff')],
    price: 48000,
    quantity: 12,
    saleType: 'fixed',
    status: 'active',
    shippingPolicyId: 'ship-1',
    createdAt: '2026-01-07',
  },
  {
    id: 'l-2',
    sellerId: 'u-2',
    variantId: 'v-2',
    conditionGrade: 'A',
    conditionDetails: ['미세 스크래치'],
    includes: {
      pob: true,
      sleeve: false,
      case: false,
      albumInclusions: ['가사지', '스티커'],
    },
    photos: [makeDisc('#10131a', '#d5ebff')],
    price: 18000,
    quantity: 20,
    saleType: 'offer',
    status: 'active',
    shippingPolicyId: 'ship-2',
    createdAt: '2026-01-07',
  },
  {
    id: 'l-3',
    sellerId: 'u-3',
    variantId: 'v-3',
    conditionGrade: 'A',
    conditionDetails: ['박스 미세 눌림'],
    includes: {
      pob: false,
      sleeve: true,
      case: true,
      albumInclusions: ['북클릿', '포스터', '디스크 케이스'],
    },
    photos: [makeDisc('#0b0d11', '#cfe8ff')],
    price: 62000,
    quantity: 9,
    saleType: 'fixed',
    status: 'active',
    shippingPolicyId: 'ship-1',
    createdAt: '2026-01-06',
  },
  {
    id: 'l-4',
    sellerId: 'u-4',
    variantId: 'v-4',
    conditionGrade: 'S',
    conditionDetails: ['라벨 상태 양호', '하자 없음'],
    includes: {
      pob: true,
      sleeve: true,
      case: true,
      albumInclusions: ['J-card', '스티커'],
    },
    photos: [makeCard('#111', '#f5d2df')],
    price: 189000,
    quantity: 3,
    saleType: 'offer',
    status: 'active',
    shippingPolicyId: 'ship-3',
    createdAt: '2026-01-05',
  },
  {
    id: 'l-5',
    sellerId: 'u-5',
    variantId: 'v-5',
    conditionGrade: 'A',
    conditionDetails: ['커버 미세 눌림'],
    includes: {
      pob: false,
      sleeve: true,
      case: true,
      albumInclusions: ['가사지', '라이너 노트'],
    },
    photos: [makeDisc('#0e1218', '#f0e8ff')],
    price: 39000,
    quantity: 7,
    saleType: 'fixed',
    status: 'active',
    shippingPolicyId: 'ship-1',
    createdAt: '2026-01-04',
  },
  {
    id: 'l-6',
    sellerId: 'u-5',
    variantId: 'v-6',
    conditionGrade: 'B',
    conditionDetails: ['케이스 스크래치', '북클릿 사용감'],
    includes: {
      pob: false,
      sleeve: false,
      case: false,
      albumInclusions: ['가사지'],
    },
    photos: [makeDisc('#0d0d0d', '#ffe7ba')],
    price: 52000,
    quantity: 5,
    saleType: 'offer',
    status: 'active',
    shippingPolicyId: 'ship-2',
    createdAt: '2026-01-03',
  },
  {
    id: 'l-7',
    sellerId: 'u-6',
    variantId: 'v-7',
    conditionGrade: 'S',
    conditionDetails: ['미개봉'],
    includes: {
      pob: true,
      sleeve: true,
      case: true,
      albumInclusions: ['북클릿', '포스터', '번호 카드'],
    },
    photos: [makeDisc('#111722', '#dce3ff')],
    price: 78000,
    quantity: 4,
    saleType: 'fixed',
    status: 'active',
    shippingPolicyId: 'ship-3',
    createdAt: '2026-01-02',
  },
  {
    id: 'l-8',
    sellerId: 'u-7',
    variantId: 'v-8',
    conditionGrade: 'A',
    conditionDetails: ['모서리 미세 스크래치'],
    includes: {
      pob: true,
      sleeve: false,
      case: false,
      albumInclusions: ['가사지', '인서트'],
    },
    photos: [makeDisc('#10131a', '#d5ebff')],
    price: 23000,
    quantity: 14,
    saleType: 'offer',
    status: 'active',
    shippingPolicyId: 'ship-2',
    createdAt: '2026-01-01',
  },
  {
    id: 'l-9',
    sellerId: 'u-8',
    variantId: 'v-9',
    conditionGrade: 'S',
    conditionDetails: ['미개봉'],
    includes: {
      pob: true,
      sleeve: true,
      case: true,
      albumInclusions: ['북클릿', '사인 북클릿', '포스터'],
    },
    photos: [makeDisc('#0b0d11', '#f4d9e5')],
    price: 45000,
    quantity: 11,
    saleType: 'fixed',
    status: 'active',
    shippingPolicyId: 'ship-1',
    createdAt: '2025-12-30',
  },
  {
    id: 'l-10',
    sellerId: 'u-9',
    variantId: 'v-10',
    conditionGrade: 'A',
    conditionDetails: ['구성품 일부 비닐 사용감'],
    includes: {
      pob: false,
      sleeve: true,
      case: true,
      albumInclusions: ['가사지', 'OBI', '스티커'],
    },
    photos: [makeDisc('#0e1218', '#f0e8ff')],
    price: 52000,
    quantity: 6,
    saleType: 'fixed',
    status: 'active',
    shippingPolicyId: 'ship-1',
    createdAt: '2025-12-28',
  },
  {
    id: 'l-11',
    sellerId: 'u-7',
    variantId: 'v-11',
    conditionGrade: 'B',
    conditionDetails: ['라벨 마모', '테이프 늘어짐'],
    includes: {
      pob: false,
      sleeve: false,
      case: false,
      albumInclusions: ['J-card'],
    },
    photos: [makeCard('#0d0d0d', '#ffe7ba')],
    price: 28000,
    quantity: 9,
    saleType: 'offer',
    status: 'active',
    shippingPolicyId: 'ship-2',
    createdAt: '2025-12-27',
  },
]

export const priceIndex = [
  { variantId: 'v-1', conditionGrade: 'S', period: '7d', medianPrice: 47000, averagePrice: 46500, lastTradePrice: 48000, tradeCount: 42 },
  { variantId: 'v-2', conditionGrade: 'A', period: '30d', medianPrice: 17000, averagePrice: 17600, lastTradePrice: 18000, tradeCount: 81 },
  { variantId: 'v-3', conditionGrade: 'A', period: '7d', medianPrice: 60000, averagePrice: 61500, lastTradePrice: 62000, tradeCount: 18 },
  { variantId: 'v-4', conditionGrade: 'S', period: 'all', medianPrice: 185000, averagePrice: 189000, lastTradePrice: 189000, tradeCount: 9 },
  { variantId: 'v-5', conditionGrade: 'A', period: '7d', medianPrice: 38000, averagePrice: 39500, lastTradePrice: 39000, tradeCount: 28 },
  { variantId: 'v-6', conditionGrade: 'B', period: '30d', medianPrice: 50000, averagePrice: 51000, lastTradePrice: 52000, tradeCount: 13 },
  { variantId: 'v-7', conditionGrade: 'S', period: 'all', medianPrice: 76000, averagePrice: 77000, lastTradePrice: 78000, tradeCount: 21 },
  { variantId: 'v-8', conditionGrade: 'A', period: '7d', medianPrice: 22000, averagePrice: 22800, lastTradePrice: 23000, tradeCount: 35 },
  { variantId: 'v-9', conditionGrade: 'S', period: '30d', medianPrice: 44000, averagePrice: 44500, lastTradePrice: 45000, tradeCount: 26 },
  { variantId: 'v-10', conditionGrade: 'A', period: '7d', medianPrice: 50000, averagePrice: 51500, lastTradePrice: 52000, tradeCount: 19 },
  { variantId: 'v-11', conditionGrade: 'B', period: '30d', medianPrice: 26000, averagePrice: 27000, lastTradePrice: 28000, tradeCount: 12 },
]

export const priceHistory = {
  'v-1': [43000, 44500, 46000, 45500, 47000, 48000, 47500],
  'v-2': [15000, 16000, 17000, 16500, 17200, 18000, 17500],
  'v-3': [56000, 58000, 60000, 59000, 61000, 62000, 61500],
  'v-4': [175000, 180000, 182000, 185000, 186000, 189000, 188000],
  'v-5': [34000, 35500, 36000, 37200, 38000, 39000, 38800],
  'v-6': [47000, 49000, 50000, 51000, 52000, 51500, 51800],
  'v-7': [70000, 72000, 74000, 75000, 76000, 78000, 77500],
  'v-8': [18000, 19500, 20500, 21500, 22000, 23000, 22800],
  'v-9': [39000, 40500, 42000, 43000, 44000, 45000, 44800],
  'v-10': [45000, 47000, 49000, 50000, 51000, 52000, 51500],
  'v-11': [24000, 25000, 26000, 26500, 27000, 28000, 27500],
}

export const shippingPolicies = {
  'ship-1': { name: '일반 배송', fee: 4000, eta: '1-2일' },
  'ship-2': { name: '반값 택배', fee: 2500, eta: '2-3일' },
  'ship-3': { name: '프리미엄 배송', fee: 6000, eta: '당일/익일' },
}

export const offers = [
  { id: 'of-1', listingId: 'l-2', buyerId: 'u-9', price: 16500, status: '대기' },
  { id: 'of-2', listingId: 'l-4', buyerId: 'u-7', price: 182000, status: '카운터' },
]

export const orders = [
  {
    id: 'o-1',
    listingId: 'l-1',
    buyerId: 'u-8',
    finalPrice: 48000,
    platformFee: 2400,
    shippingFee: 4000,
    status: 'shipped',
    trackingNumber: 'CJ1234',
    timestamps: { paid: '오늘 10:00', shipped: '오늘 14:20' },
  },
]
